# Numpy 패키기
- 난수 생성
- 선형대수

In [1]:
import numpy as np

# Array 구조
- np array

In [3]:
data1 = [1, 2, 3, 4, 5]
data1

[1, 2, 3, 4, 5]

In [4]:
arr1 = np.array(data1)
arr1

array([1, 2, 3, 4, 5])

In [5]:
type(data1)

list

In [6]:
type(arr1)

numpy.ndarray

- ndim: 축의 개수

In [9]:
arr1.ndim

1

- shape: array의 크기 및 형태

In [7]:
arr1.shape

(5,)

- dtype: 데이터유형 확인

In [8]:
arr1.dtype

dtype('int64')

- 2차원 구조

In [11]:
arr2 = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
print(arr2)
print(arr2.ndim)
print(arr2.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
2
(4, 3)
