# Array의 연산
- 기본적으로 numpy에서연산을 할때는 크기가 서로 동일한 array끼리 연산이 진행
- 이때 같은 위치에 있는 요소들 끼리 연사이 진행

In [2]:
import numpy as np

In [3]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
arr1.shape

(2, 3)

In [6]:
arr2 = np.array([[10, 11, 12], [13,14,15]])
arr2

array([[10, 11, 12],
       [13, 14, 15]])

In [7]:
arr2.shape

(2, 3)

In [9]:
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)

[[11 13 15]
 [17 19 21]]
[[-9 -9 -9]
 [-9 -9 -9]]
[[10 22 36]
 [52 70 90]]
[[0.1        0.18181818 0.25      ]
 [0.30769231 0.35714286 0.4       ]]


- array의 브로드 캐스트
    - 위에서는 array가 같은 크기를 가져야 서로 연산이 가능하다고 했지만, numpy에서는 브로드캐스트라는 기능을 제공
    - 브로드캐스트란, 서로 크기가 다른 array가 연산이 가능하게끔 하는 것

In [10]:
arr3 = np.array([10, 11, 12])
arr3

array([10, 11, 12])

In [11]:
print(arr1+arr3)

[[11 13 15]
 [14 16 18]]


- 위와 같이 서로 크기가 다른 arr1과 arr3의 연산이 가능
- 연산결과를 살펴보면 arr3가 [10, 11, 12]에서 [[10, 11, 12], [10, 11, 12]]로 확장되어 계산됨을 확인할 수 있음
- array형태끼리 뿐만 아니라 스칼라도 연산이 가능함

In [12]:
print(arr1+10)
print(arr1**2)

[[11 12 13]
 [14 15 16]]
[[ 1  4  9]
 [16 25 36]]
