# random 모듈

In [1]:
import numpy as np

- np.random.randint()

In [2]:
np.random.randint(6)# 0~5사이의 숫자 랜덤 추출

1

In [3]:
np.random.randint(1, 20)# 1~19사이의 숫자 랜덤 추출

5

In [4]:
np.random.randint(1, 20, size=10)

array([ 2, 18, 12, 16, 18,  7, 10, 12,  5,  3])

- np.random.rand(): 0~1의 균일분포

In [5]:
np.random.rand(6)

array([0.07394849, 0.6214571 , 0.44738706, 0.9898419 , 0.59340274,
       0.02412512])

In [6]:
np.random.rand(3,2)

array([[0.20677684, 0.90655011],
       [0.61734345, 0.59574705],
       [0.35884894, 0.96079973]])

- np.random.randn(): 평균0, 표준편차가 1인 표준정규분포에서 랜덤 추출

In [7]:
np.random.randn(3, 2)

array([[-0.41657982, -1.31412623],
       [-1.62480677, -0.16211968],
       [ 0.87936683,  1.81457603]])

- np.random.seed(): 동일한 랜덤추출된 숫자를 사용

In [6]:
np.random.seed(1004)
np.random.rand(3,2)

array([[0.03895164, 0.85649586],
       [0.74650031, 0.86392789],
       [0.55998441, 0.08048307]])

- np.random.shuffle(): 데이터 순서를 랜덤하게 바꿈

In [7]:
np.random.seed(1004)
data = np.random.rand(3,2)
data

array([[0.03895164, 0.85649586],
       [0.74650031, 0.86392789],
       [0.55998441, 0.08048307]])

In [8]:
np.random.shuffle(data)
data

array([[0.03895164, 0.85649586],
       [0.55998441, 0.08048307],
       [0.74650031, 0.86392789]])

- np.random.choice(): 기존 데이터에서 랜덤하게 추출

In [9]:
data = ['apple', 'banana', 'strawberry']
np.random.choice(data)

np.str_('apple')

In [10]:
np.random.choice(data, 2)

array(['apple', 'apple'], dtype='<U10')

In [11]:
np.random.choice(data, 2, p=[0.1, 0.5, 0.4])

array(['banana', 'apple'], dtype='<U10')

- np.unique(): 중복 제거

In [12]:
data = ['apple', 'apple', 'strawberry']
np.unique(data)

array(['apple', 'strawberry'], dtype='<U10')