# Numpy 패키기

In [ ]:
import numpy as np

## 문제 1. 3*2행렬 구조로 Array 형태 데이터 A, B를 생성하고, + 연산한 Array를 구하라
    - A: [2,3,4,5,6,7]
    - B: [1,1,3,3,5,5]

In [14]:
A=[2,3,4,5,6,7]
B=[1,1,3,3,5,5]
A = np.array(A)
B = np.array(B)
A+B

array([ 3,  4,  7,  8, 11, 12])

## 문제 2. 1~100 사이의 정수 중 랜덤하게 한 개의 숫자 추출

In [44]:
np.random.randint(100)+1

100

    - MAX, MIN 값 확인

In [45]:
xs = []
for i in range(10000):
    xs.append(np.random.randint(100)+1)

xs = np.array(xs)
print(f"max:{xs.max()}, min:{xs.min()}")

max:100, min:1


## 문제 3. 실 데이터 활용
    - 제공한 PDF feature 2개 결합
    - 결합한 데이터에서 랜덤 데이터 추출

In [57]:
import pandas as pd
in_file1 = "Data/file_00_0.csv"
in_file2 = "Data/file_00_1.csv"
np_array1 = pd.read_csv(in_file1, index_col=0).T.iloc[0, 1:].values
np_array1 = np_array1.astype(np.float64)
np_array2 = pd.read_csv(in_file2, index_col=0).T.iloc[0, 1:].values
np_array2 = np_array2.astype(np.float64)
print(np_array1)
print(np_array2)

[  0.      0.      0.      0.      0.      0.      0.      0.      0.
   0.      0.      2.      0.      1.     94.     90.      8.      0.
   0.      1.      2.      0.      1.      7.      0.      0.      0.
  32.      2.      0.      1.      4.      2.     97.    110.      3.
   2.      0.      0.      0.      0.      0.      0.      0.      0.
   0.      0.      0.      0.     15.      0.      0.    195.771 232.
   0.      0.   ]
[ 2.     0.     0.     0.     0.     0.     1.     0.     0.     1.
  0.     0.     1.     0.     1.     0.     0.     0.     0.     1.
  1.     0.     1.     0.     0.     0.     0.     0.     0.     0.
  1.     0.     0.     3.     2.     0.     0.     0.     0.     0.
  1.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 11.    11.     2.112  4.     0.     0.   ]


In [59]:
np_array = np_array1+np_array2
print(np_array)
np.random.choice(np_array, 10)

[  2.      0.      0.      0.      0.      0.      1.      0.      0.
   1.      0.      2.      1.      1.     95.     90.      8.      0.
   0.      2.      3.      0.      2.      7.      0.      0.      0.
  32.      2.      0.      2.      4.      2.    100.    112.      3.
   2.      0.      0.      0.      1.      0.      0.      0.      0.
   0.      0.      0.      0.     15.     11.     11.    197.883 236.
   0.      0.   ]


array([0., 0., 2., 3., 1., 0., 1., 0., 0., 0.])

    - Index를 포함한 random selection

In [65]:
import random
r_indexs = []
for i in range(10):
    r_value = random.choice(range(np_array.shape[0]))
    while r_value in r_indexs:
        r_value = random.choice(range(np_array.shape[0]))
    r_indexs.append(r_value)
r_indexs = np.array(r_indexs)
print(r_indexs)

[14 19  3  4 52 25 38 45 41 33]


In [66]:
r_values_dict = {}
for rindex in r_indexs:
    r_values_dict[rindex] = np_array[rindex]
print(r_values_dict)

{14: 95.0, 19: 2.0, 3: 0.0, 4: 0.0, 52: 197.88299999999998, 25: 0.0, 38: 0.0, 45: 0.0, 41: 0.0, 33: 100.0}
